# Gradle properties for Android

# Project-wide Gradle settings
org.gradle.jvmargs=-Xmx2048m

# Enable support for Jetpack Compose
android.useAndroidX=true
android.enableJetifier=true

# Whether to enable Android Gradle plugin's new compose compiler
android.enableComposeCompiler=true

# Configure build cache 
android.enableBuildCache=true

# Enable Gradle daemon temporarily for faster builds.
org.gradle.daemon=true
